apiVersion: apps/v1
kind: Deployment
metadata:
  name: just-try-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: just-try
  template:
    metadata:
      labels:
        app: just-try
    spec:
      containers:
        - name: just-try
          image: badshanoordeen/just-try:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: just-try-service
spec:
  selector:
    app: just-try
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
